@rootUrl = http://localhost:8001

#API list

### Check server status
Get {{rootUrl}}

### Auth API

### Post new user
POST {{rootUrl}}/api/v1/auth/register
Content-Type: application/json

{
    "fName" : "Rohith",
    "lName" : "Kumar",
    "email" : "abc2@g.com",
    "phone" : "9876543210",
    "address" : {
        "street": "PointCook",
        "city": "Melbourne",
        "state": "Victoria",
        "zipcode": "3030",
        "country": "Australia"
    },
    "password" : "Roh@123"
}